# Generated by Django 6.0.5 on 2026-05-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Programming', 'Programming'), ('Romantic', 'Romantic'), ('Science Fiction', 'Science Fiction')], max_length=50)),
                ('description', models.TextField()),
                ('image', models.URLField(blank=True, default='https://via.placeholder.com/120?text=No+Image')),
            ],
        ),
    ]
